development:
  adapter: postgresql
  encoding: unicode
  database: lost_tribes2_dev
  pool: 5
  username: ryankuhel
  host: localhost
  password:


test:
  adapter: postgresql
  encoding: unicode
  database: lost_tribes2_dev
  pool: 5
  username: ryankuhel
  host: localhost
  password:
