development:
  adapter: postgresql
  encoding: unicode
  database: lost_tribes2_dev
  pool: 5
  username: chriseichler
  host: localhost
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: lost_tribes2_test
  pool: 5
  username: chriseichler
  host: localhost
  password: